ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_ENV=development
    init: |
      docker-compose pull
      pip install -r requirements.txt
      flask init-db
    command: |
      docker-compose up -d
      export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
