ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_ENV=development
    init: |
      echo 'export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"' >> ~/.bashrc
      docker-compose pull
      pip install -r requirements.txt
    command: |
      docker-compose up -d
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
